//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Account
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Account()
    {
        this.Articles = new HashSet<Article>();
        this.ArticleCategories = new HashSet<ArticleCategory>();
        this.ArticleMainCategories = new HashSet<ArticleMainCategory>();
        this.Contacts = new HashSet<Contact>();
        this.ContactCategories = new HashSet<ContactCategory>();
        this.Products = new HashSet<Product>();
        this.ProductCategories = new HashSet<ProductCategory>();
        this.ProductMainCategories = new HashSet<ProductMainCategory>();
    }

    public string Username { get; set; }
    public string Password { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public string FullName { get; set; }
    public string Email { get; set; }
    public string Mobi { get; set; }
    public string Address { get; set; }
    public Nullable<bool> Gender { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string AccountCategoryID { get; set; }

    public virtual AccountCategory AccountCategory { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Article> Articles { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ArticleCategory> ArticleCategories { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ArticleMainCategory> ArticleMainCategories { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Contact> Contacts { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ContactCategory> ContactCategories { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Product> Products { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductCategory> ProductCategories { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductMainCategory> ProductMainCategories { get; set; }
}

public partial class AccountCategory
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AccountCategory()
    {
        this.Accounts = new HashSet<Account>();
    }

    public string AccountCategoryID { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Account> Accounts { get; set; }
}

public partial class Article
{
    public int ArticleID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public string Content { get; set; }
    public string Keyword { get; set; }
    public string ImageList { get; set; }
    public string SourcePage { get; set; }
    public string SourceLink { get; set; }
    public string AttachmentFile { get; set; }
    public Nullable<int> ViewTime { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public Nullable<int> ArticleCategoryID { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    public virtual ArticleCategory ArticleCategory { get; set; }
}

public partial class ArticleCategory
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ArticleCategory()
    {
        this.Articles = new HashSet<Article>();
    }

    public int ArticleCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public Nullable<int> ArticleMainCategoryID { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Article> Articles { get; set; }
    public virtual ArticleMainCategory ArticleMainCategory { get; set; }
}

public partial class ArticleMainCategory
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ArticleMainCategory()
    {
        this.ArticleCategories = new HashSet<ArticleCategory>();
    }

    public int ArticleMainCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ArticleCategory> ArticleCategories { get; set; }
}

public partial class Contact
{
    public int ContactID { get; set; }
    public string Code { get; set; }
    public string FullName { get; set; }
    public string Email { get; set; }
    public string Address { get; set; }
    public string Mobi { get; set; }
    public string Content { get; set; }
    public string AttachmentFile { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string ApproveBy { get; set; }
    public Nullable<int> ContactCategoryID { get; set; }

    public virtual Account Account { get; set; }
    public virtual ContactCategory ContactCategory { get; set; }
}

public partial class ContactCategory
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ContactCategory()
    {
        this.Contacts = new HashSet<Contact>();
    }

    public int ContactCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Contact> Contacts { get; set; }
}

public partial class Product
{
    public int ProductID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public string Content { get; set; }
    public string Keyword { get; set; }
    public string ImageList { get; set; }
    public string GalleryImageList { get; set; }
    public string SourcePage { get; set; }
    public string SourceLink { get; set; }
    public Nullable<int> ViewTime { get; set; }
    public string AttachmentFile { get; set; }
    public Nullable<double> Price { get; set; }
    public Nullable<double> OldPrice { get; set; }
    public string Promotions { get; set; }
    public string WarrantyPolicy { get; set; }
    public string Specifications { get; set; }
    public string Accessories { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }
    public Nullable<int> ProductCategoryID { get; set; }

    public virtual Account Account { get; set; }
    public virtual ProductCategory ProductCategory { get; set; }
}

public partial class ProductCategory
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProductCategory()
    {
        this.Products = new HashSet<Product>();
    }

    public int ProductCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }
    public Nullable<int> ProductMainCategoryID { get; set; }

    public virtual Account Account { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Product> Products { get; set; }
    public virtual ProductMainCategory ProductMainCategory { get; set; }
}

public partial class ProductMainCategory
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProductMainCategory()
    {
        this.ProductCategories = new HashSet<ProductCategory>();
    }

    public int ProductMainCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductCategory> ProductCategories { get; set; }
}
